using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace EcoSimulator
{
    public class Plant : MonoBehaviour
    {
        // age related
        // -----------

        public float lifeTime = 150F; //!< plant life time in years
        public float age = 0F;  //!< Current plant age
        public float seedingTime = 0F; //!< time since the plant started seeding (when became mature)

        // size related
        // ------------
        public float radius = 0F; //!< Current radius
        public float survivalRadius = 1F; //!< Radius at which the plant survives
        public float maturityRadius = 2.5F; //!< size at which the plant stops growing and starts seeding (in meters)
        public float growingSpeed = 0.2F;   //!< radius growth in meters per year


        //// light/resources related
        //// -----------------------

        //public float canopyOpacity = 0.5F; //!< Percent of light reaching ground under the plant
        ////public float shadeTolerence = 0.0F; //!< Ability of the plant to grow in the shade of other
        //public float neededLightToGrow = 0.5F; //!< light factor need by the seed to start growing

        // Seeding related
        // ---------------

        public float seedingRadius = 20F; //!< radius of seeds spreading in meters
        public int seedingCapacity = 50; //!< mean number of seeds generated by the plant (per year)

        public int generation = 0;

        Collider mycollider = null;

        //public float CrownSize
        //{
        //    get
        //    {
        //        return (mycollider as CapsuleCollider).radius * transform.localScale.x;
        //    }
        //}

        public bool IsMature { get { return radius >= maturityRadius; } }

        public Vector3 initScale = Vector3.one;

        // Use this for initialization
        void Awake()
        {
            initScale = transform.localScale;
            mycollider = GetComponent<Collider>();
        }

        public void Grow(float deltaTime)
        {
            if (domined > 0)
                return;
            radius += growingSpeed * deltaTime;
            SetRadius();
        }

        float colRadius = -1F;
        public void SetRadius()
        {
             if(colRadius <0F)
                colRadius = (mycollider as CapsuleCollider).radius;// * transform.localScale.x;
            float s = (radius * initScale.x) / colRadius;
            transform.localScale = initScale * (s / initScale.x);
        }

        int seeds = 0;
        void LateUpdate()
        {
            if (domined>0 && radius < survivalRadius)
            {
                Destroy(gameObject);
                return;
            }


            float elapsedTime = Time.deltaTime * 10F; // 1 s is 10 years

            if (!IsMature)
                Grow(elapsedTime);
            else
            {
                if (seeds / seedingTime < seedingCapacity)
                    Seed();

                seedingTime += elapsedTime;
            }

            age += elapsedTime;
            if (age > lifeTime)
                GameObject.Destroy(gameObject);

        }

        //void OnTriggerEnter(Collider other)
        //{
        //    Debug.Log("collision");
        //    //Destroy(other.gameObject);
        //}

        int domined = 0;

        void OnCollisionEnter(Collision collision)
        {
            if (collision.collider == EcoSimulatorManager.Instance.water)
            {
                Destroy(gameObject);
                return;
            }
            if (collision.collider != EcoSimulatorManager.Instance.ground)
            {
                Plant concurrent = collision.collider.gameObject.GetComponent<Plant>();
                if (concurrent == null)
                    return;

                if (concurrent.radius > radius)
                    domined++;
                else
                    concurrent.domined++;
                //    Destroy(gameObject);//collision.collider.gameObject);
                //else
                //    Destroy(collision.collider.gameObject);
            }
        }

        void OnCollisionExit(Collision collision)
        {
            if (collision.collider != EcoSimulatorManager.Instance.ground)
            {
                Plant concurrent = collision.collider.gameObject.GetComponent<Plant>();
                if (concurrent == null)
                    return;

                if (concurrent.radius > radius)
                    domined--;
                else
                    concurrent.domined--;
                //    Destroy(gameObject);//collision.collider.gameObject);
                //else
                //    Destroy(collision.collider.gameObject);
            }
        }

        void Seed()
        {
            if (EcoSimulatorManager.Instance == null)
                return;

            seeds++;

            Vector3 pos = transform.position;

            //for (int i = 0; i < seedingCapacity; i++)
            {
                Vector3 offset = new Vector3(Random.Range(-1F, 1F), 0, Random.Range(-1F, 1F));
                Vector3 seedPos = pos + (offset.normalized * Random.Range(0F, 1F)*seedingRadius);
                Ray ray = new Ray(seedPos + Vector3.up * 10000F, Vector3.down);
                //Debug.DrawRay(ray.origin, ray.direction * 100000F, Color.red, 1F);
                RaycastHit info;
                //if (!EcoSimulatorManager.Instance.ground.Raycast(ray, out info, 100000))
                //    return;// continue;
                //seedPos = ray.GetPoint(info.distance);
                {
                    RaycastHit[] all = Physics.RaycastAll(ray);
                    if (all.Length == 0)
                        return;

                    float waterDist = Mathf.Infinity;
                    float groundDist = Mathf.Infinity-1F;
                    foreach (RaycastHit rh in all)
                    {
                        if (rh.collider == EcoSimulatorManager.Instance.water)
                            waterDist = rh.distance;
                        if (rh.collider == EcoSimulatorManager.Instance.ground)
                        {
                            seedPos = ray.GetPoint(rh.distance);
                            groundDist = waterDist = rh.distance;
                        }
                    }

                    if (waterDist < groundDist)
                        return;
                }

                ray = new Ray(seedPos, Vector3.up);

                if(Physics.Raycast(ray, out info, 50F))
                {
                    Plant above = info.collider.gameObject.GetComponent<Plant>();
                    if(above != null)
                    {
                        return;//continue;
                    }
                }

                GameObject child = Instantiate(gameObject);
                child.name = name;
                //child.transform.parent = transform;
                child.transform.position = seedPos;
                child.transform.localRotation = Quaternion.Euler(Random.Range(-5, 5), Random.Range(-180, 180), Random.Range(-5, 5));
                child.hideFlags = HideFlags.HideInHierarchy | HideFlags.HideInInspector;

                Plant seed = child.GetComponent<Plant>();
                seed.generation = generation + 1;
                seed.initScale = initScale;// * Random.Range(0.7F,1.5F);
                seed.radius = 0F;
                seed.seedingTime = 0F;
                seed.age = 0F;
                seed.SetRadius();
            }
        }
    }
}
